### PR TITLE
Rename arguments of list_evaluations

### PR DESCRIPTION
**Pull request by Bilgecelik**
#804

### CODE REVIEW

**Comment by PGijsbers** [comment]
Looks good! Waiting for pending PRs, but otherwise ready for merge! :)

**Comment by mfeurer** [comment]
Hey @Bilgecelik, the newly introduce black code checker is unhappy about at least one of the files. Could you please update your code? [Here](https://github.com/openml/openml-python/blob/develop/CONTRIBUTING.md)'s some more info on how to run black locally.

**Comment by PGijsbers** [comment]
Very peculiar that you were still able to commit. Maybe `pre-commit` wasn't installed? I know you just switched repo so it can be easy to forget (new) parts of the setup. Please let me know if you figure out why black was bypassed locally.

**Comment by Bilgecelik** [comment]
Hmm i did pre-commit but i will try again. The sklearn extension files were problematic before commit but weren't my files. I will check.

**Comment by PGijsbers** [comment]
thanks 🎉

**Pull request merged**
