### PR TITLE
Migrate to Pytest

### PR DESCRIPTION
**Pull request by rth**
Closes https://github.com/openml/openml-python/issues/327

nose is not longer maintained and most popular packages in the scientific python community have migrated to pytest. The existing tests will run without modifications with pytest, but it will make easier,
 - cleaning up temporary files (https://github.com/openml/openml-python/issues/447)
 - running some tests without actually connecting to the server without using mock responses, as it e.g. done in the openml loaded in scikit-learn.

### CODE REVIEW

**Comment by rth** [comment]
CI is green. 

What do you think about this @mfeurer @janvanrijn ?

**Comment by rth** [comment]
So, `pip install` is now the recommended way to install packages (even local packages) as compared to `python setup.py install` (see https://packaging.python.org/tutorials/installing-packages/#installing-from-a-local-src-tree).

```
pip install .  # dot important at the end
```
installs the local package.

To get the behaviour of `develop`, it's necessary to add the `-e` flag.

And to install extra dependencies, one would do,
```
pip install openml[test]
```
which installs extra "test" dependencies specified in the `setup.py`. So the sum of that in this case is,
```
pip install -e .[test]
```
with some paranthesis as I wasn't sure how bash would handle it.

**Comment by mfeurer** [comment]
Thanks a lot for explaining this. I just talked to @janvanrijn and he's okay with merging this. Thanks a lot!

**Comment by rth** [comment]
Thanks for the review @mfeurer !

**Pull request merged**
