### PR TITLE
Fix: update fetching a bucket from MinIO

### PR DESCRIPTION
**Pull request by eddiebergman**
Closes: #1304 

Branch by @PGijsbers, just created a PR from it

--- 

Previously, each dataset had their own bucket:
  https://openml1.win.tue.nl/datasets61/dataset_61.pq

But we were advised to reduce the amount of buckets and favor hosting many objects in hierarchical structure, so we now have instead some prefixes to divide up the dataset objects into separate subdirectories:

  https://openml1.win.tue.nl/datasets/0000/0061/dataset_61.pq

This commit has bypassed pre-commit. Tests should be updated too.

### CODE REVIEW

**Review by LennartPurucker — APPROVED** [review]

**Review by LennartPurucker — CHANGES_REQUESTED** [review]
Based on the tests, we assume something breaks on the server side now. 

Production-based tests like test_get_data_array do not finish. Is MinIO down? @josvandervelde

**Comment by eddiebergman** [comment]
Hi @josvandervelde,

Just pinging this issue again. I reran the tests to see where it fails which you can find here: https://github.com/openml/openml-python/actions/runs/7527320791

If you need to run them manually, you can do so from `Actions -> Test -> Run Workflow`. Otherwise, committing to this branch will also trigger them :)

**Comment by eddiebergman** [comment]
They seemed to pass, I'm going to try create an empty commit to have it display here

**Comment by eddiebergman** [comment]
Seems the only issue was uploading the code coverage with a server error, otherwise this seems all good now :)

**Comment by LennartPurucker** [comment]
Yup, sorry, this is fine to merge now. And we can do a release afterwards @eddiebergman

**Review by LennartPurucker — APPROVED** [review]

**Pull request merged**
