### PR TITLE
Add: workflow to update precommit

### PR DESCRIPTION
**Pull request by eddiebergman**
Checks everyday to create PR that is to update pre-commit hooks 

See #1153

### CODE REVIEW

**Comment by PGijsbers** [comment]
>  you may want to have the updates as part of the release

Which they will be... the next release. These dependencies are only for developers and govern the code formatting/guidelines and generally have no effect on the functionality of the tool.

> So this should only make changes to the pre-commit config file which shouldn't cause merge conflicts

Only updating the pre-commit file without updating the affected files may lead to a state where CI will do a pre-commit check to make sure everything is formatted/type-hinted correctly and fail. This can happen when e.g., black's formatting rules update and would reformat some files. That said, it shouldn't be hard to update the workflow to add that step to the PR.

**Comment by eddiebergman** [comment]
Yup, your points makes sense, I'll change it later today.

Regarding updates causing format conflicts, most common precommit hooks that would format code are fairly stable, i.e. their updates are primarily new functionality, covering new features, optimizations and weird edge cases. I've had to update mypy once for it to recognize valid typing I wrote but that's the only time an updated pre-commit made a meaningful difference for me.

Best,
Eddie

**Comment by PGijsbers** [comment]
Our last bump changed 50 files (#1150). Granted, we had not updated the dependencies since we added the pre-commit hooks, but that was "just" under 2 years ago. I do concede that the times the dependencies actually change formatting will not be common (most edits will be caused by one or two specific version bumps). Auto-updating the pre-commit file only without showing the affected files (if any) does not seem all that useful to me since I wouldn't do a blind merge for the above reasons and thus still need to figure out which (if any) files are affected manually. But adding a step in the job with `pre-commit run --all-files` before pushing the changes for a PR would likely solve that issue (provided CI reports the `mypy` problems).

**Comment by eddiebergman** [comment]
That's also a great point, I'll add those as extra steps :)

**Pull request closed without merging**
