### PR TITLE
Remove archive after it is extracted to save disk space

### LINKED ISSUE #1348: Add clean up function for downloaded image archive
Currently the image archive sticks around, but we probably don't want that by default.

cf. https://github.com/openml/openml-python/blob/de983ac5a313319ff0d2f3528f609a49d767382e/openml/_api_calls.py#L172

### PR DESCRIPTION
**Pull request by PGijsbers**
Closes #1348

I don't really know that we need to make this configurable at this point. Let's not add more options for now, and see if we get requests.

### CODE REVIEW

**Comment by PGijsbers** [comment]
@prabhant This is what you are looking for, right?

**Comment by prabhant** [comment]
Looks good to me

**Comment by PGijsbers** [comment]
It just sprang to my mind that removing the file does conflict with the caching mechanism, so it will likely always download the archive now... What would be a good way to resolve that? Leaving some kind of empty marker with the same name is a quick hack. @LennartPurucker @eddiebergman

**Comment by eddiebergman** [comment]
Interesting, I came across this exact problem recently where I don't know the contents of tarfiles directly and needed to check if their content were already present. I didn't implement a solution other than `force: bool` but your idea about a marker sounds promising. It would assume that the any new tarfiles that might be downloaded are uniuly named, such that you can one-to-one map them to a marker file.

I don't have a good solution but please keep me posted if you come up with one!

**Review by LennartPurucker — CHANGES_REQUESTED** [review]
Yea, I agree. A marker file for the file being already extracted would be needed and an option to still force the download (force bool or cleaning up the cache). 

Ideally, we would have a uuid for the content of the zip file on the server that, if it changes, would prompt us to re-download. Then, we would just name the marker file using this uuid and check for a match before downloading and extracting again.

**Comment by PGijsbers** [comment]
In this case we can apparently use the metadata which contains a hash (at least, as far as I can tell, that's what it is). For a force refresh, we already support that at a get_dataset level, so I didn't think we need to do anything special here.

**Review by LennartPurucker — APPROVED** [review]
Very nice, LGTM, thanks!

**Pull request merged**
