### PR TITLE
Clean up usage docs

### PR DESCRIPTION
**Pull request by rhiever**
I cleaned up the verbiage a little bit. The major fix is calling the `get_data` instead of `get_dataset` function when actually pulling the data from the server.

### CODE REVIEW

**Comment by mfeurer** [comment]
Could you please rebase this PR to the latest version of the development branch so we have CI working again?

**Comment by mfeurer** [comment]
I accidentally clicked the wrong button. Sorry for that.

**Comment by rhiever** [comment]
Done!

**Comment by mfeurer** [comment]
Thanks a lot. If you want to do more on this you might figure out why the doctests did not trigger?

**Pull request merged**
