### PR TITLE
Debugging unit test for stochastic failure

### PR DESCRIPTION
**Pull request by Neeratyoy**
#### What does this PR implement/fix? Explain your changes.
Debugs the random failure of [status check](https://github.com/openml/openml-python/blob/develop/tests/test_datasets/test_dataset_functions.py#L529) during a unit test of dataset upload and explicit change of status to _active_.

### CODE REVIEW

**Comment by PGijsbers** [comment]
Is still still relevant or can we go ahead and close this?

**Comment by Neeratyoy** [comment]
I think I created this as a placeholder or reminder to check why the `test_data_edit` unit test fails randomly and if we can find a pattern to reproduce the error somehow.
However, it's been long and not sure if the new unit tests have indirectly fixed it.
I can pursue it if you think it is a problem worth tackling.

**Comment by PGijsbers** [comment]
Any flakiness is worth fixing. That said, it would be great if you can see whether or not this flakiness still exists.
Next time if you want a reminder of something to do, please create an issue instead 👍

**Comment by Neeratyoy** [comment]
Closing this.
Was unable to recreate the stochastic failures from `test_datasets/` locally on the current `develop` branch.

**Pull request closed without merging**
