### PR TITLE
FIX allow to load sparse data

### PR DESCRIPTION
**Pull request by mfeurer**
Second split of #150

### CODE REVIEW

**Comment by mfeurer** [comment]
@amueller ready to be reviewed/merged

**Comment by amueller** [comment]
I'm not entirely sure I understand this. So the user decides how to store the data? Or is the format in the ARFF different? Or does the information come from the dataset info on openml?

**Comment by mfeurer** [comment]
The arff format is different. Ideally, the parser would figure that out itself, but it doesn't. The information comes from the dataset info in openml.

**Comment by amueller** [comment]
Can't we snoop it from the file?

**Comment by mfeurer** [comment]
Would be possible. But this solution is definitely easier and faster.

**Comment by amueller** [comment]
I guess this is fine for now.

**Comment by amueller** [comment]
btw, @raghavrv what happened to your arff reader?

**Comment by joaquinvanschoren** [comment]
Openml tells you if the dataset is arff or sparse arff.

**Pull request merged**
