### PR TITLE
Fixing dataset_id referenced before assignment 

### PR DESCRIPTION
**Pull request by Neeratyoy**
#### Reference Issue

Addreses #608.

#### What does this PR implement/fix? Explain your changes.
Adds an else to handle the condition and raises an error.

#### How should this PR be tested?
`import openml`
`run = openml.runs.get_run(186276)`

#### Any other comments?
Enters an else block if input_data key is not present. Error is raised if inside else and `from_server=False`.

### CODE REVIEW

**Comment by Neeratyoy** [comment]
> ... should be reported to us (so that we can sanitize the server).

Should the message be to raise an issue [here](https://github.com/openml/openml-python/issues) or report at openml@googlegroups.com?

**Comment by PGijsbers** [comment]
Sorry for not pointing you in the right direction immediately. I think the best is to open an issue at https://github.com/openml/OpenML/issues
@janvanrijn agreed?

**Comment by Neeratyoy** [comment]
> Actually, perhaps just having an issue that we can refer to directly might be best, so people don't open a new issue for every run (and also, so that it's easier for them to check which ids have been reported).

That makes a lot of sense. Do I open an issue and update the URL in the warning message?

**Comment by PGijsbers** [comment]
I got in touch with Jan over this. There seems to have been some miscommunication.
It is not only okay for a run not to reference a dataset, but we do not want to change the instances where this is not present either.

This means we should retrieve the task to determine the dataset id.
I would still only do this if the `run['oml:input_data']['oml:dataset']['oml:did']` data is not provided (i.e. where currently the exception is raised), as this requires an extra server roundtrip.

Sorry for mixed instructions.

**Comment by Neeratyoy** [comment]
To clarify, instead of raising an error and terminating, we shall now fetch the dataset via Run -> Task -> Dataset and populate `run['oml:input_data']` ?

**Comment by PGijsbers** [comment]
> To clarify, instead of raising an error and terminating, we shall now fetch the dataset via Run -> Task -> Dataset 

Yes. The task id is already [parsed earlier in the function](https://github.com/openml/openml-python/blob/develop/openml/runs/functions.py#L633).

> and populate run['oml:input_data']

No. It just needs to be stored in `dataset_id` as it would if it had received a complete xml description.

**Pull request merged**
