### PR TITLE
Fix docstring

### PR DESCRIPTION
**Pull request by janvanrijn**

### CODE REVIEW

**Comment by mfeurer** [comment]
Hey, could you please check the failing unit test:
```
======================================================================
ERROR: test__get_task (tests.test_tasks.test_task_functions.TestTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/openml/openml-python/tests/test_tasks/test_task_functions.py", line 117, in test__get_task
    production_task = openml.tasks.get_task(34536)
  File "/home/travis/build/openml/openml-python/openml/tasks/functions.py", line 297, in get_task
    raise e
OpenMLServerException: https://www.openml.org/api/v1/xml/data/features/1176 returned code 272: No features found
```
The dataset in question is deactivated, but why does this stop the API delivering the features?

**Comment by janvanrijn** [comment]
I was wondering exactly the same. This week I am recalculating all data features with the evaluation engine, which hasn't happened in a long time. In the meantime, the XSD schema's have become more strict, i.e., only allowing feature names with [basic latin](http://www.unicode.org/reports/tr44/) characters. This dataset (and several others, i.e., 1176, 4537, 41102, 41112, 41113, 41114, 41115, 41116) does not ad-hire to this definition. 

Looking at the broader picture, what do you think is the solution to this? My preferred solution would be: deactivate these datasets, re-upload them with basic latin feature names and keep this strict check (make it more visible as well). Another less preferred option is to re-allow all types of characters in feature names.

**Comment by janvanrijn** [comment]
Opened an issue for discussion here: https://github.com/openml/openml-python/issues/501

For now, let's skip the live part of the testcase

**Comment by mfeurer** [comment]
Seems like we should replace python3.4 by python3.7 in the tests. Also, please fix the doctest.

**Comment by janvanrijn** [comment]
While we're at it, shall we also do a flake8 test? (Automatically tests
code standards, such as indentation of docstrings)

Op vrijdag 10 augustus 2018 heeft Matthias Feurer <notifications@github.com>
het volgende geschreven:

**Comment by mfeurer** [comment]
For SMAC we use codacy, we could set it up for OpenML, too. But in a new PR, please ;)

**Comment by janvanrijn** [comment]
Two doctests fail:
```
File "/home/travis/build/openml/openml-python/doc/usage.rst", line 128, in usage.rst
Failed example:
    print(tasks.columns)
Expected:
    Index(['tid', 'ttid', 'did', 'name', 'task_type', 'status',
           'estimation_procedure', 'evaluation_measures', 'source_data',
           'target_feature', 'MajorityClassSize', 'MaxNominalAttDistinctValues',
           'MinorityClassSize', 'NumberOfClasses', 'NumberOfFeatures',
           'NumberOfInstances', 'NumberOfInstancesWithMissingValues',
           'NumberOfMissingValues', 'NumberOfNumericFeatures',
           'NumberOfSymbolicFeatures', 'cost_matrix'],
          dtype='object')
Got:
    Index(['tid', 'ttid', 'did', 'name', 'task_type', 'status',
           'estimation_procedure', 'evaluation_measures', 'source_data',
           'target_feature', 'MajorityClassSize', 'MinorityClassSize',
           'NumberOfClasses', 'NumberOfFeatures', 'NumberOfInstances',
           'NumberOfInstancesWithMissingValues', 'NumberOfMissingValues',
           'NumberOfNumericFeatures', 'NumberOfSymbolicFeatures', 'cost_matrix',
           'MaxNominalAttDistinctValues'],
          dtype='object')
```
I don't understand, nothing is supposed to have changed here. Since when is this doctest active and who wrote it? 

```
File "/home/travis/build/openml/openml-python/doc/usage.rst", line 227, in usage.rst
Failed example:
    tasks = openml.tasks.get_tasks(ids)
Exception raised:
    Traceback (most recent call last):
      File "/home/travis/miniconda/envs/testenv/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest usage.rst[25]>", line 1, in <module>
        tasks = openml.tasks.get_tasks(ids)
      File "/home/travis/build/openml/openml-python/openml/tasks/functions.py", line 263, in get_tasks
        tasks.append(get_task(task_id))
      File "/home/travis/build/openml/openml-python/openml/tasks/functions.py", line 297, in get_task
        raise e
      File "/home/travis/build/openml/openml-python/openml/tasks/functions.py", line 291, in get_task
        dataset = get_dataset(task.dataset_id)
      File "/home/travis/build/openml/openml-python/openml/datasets/functions.py", line 337, in get_dataset
        features = _get_dataset_features(did_cache_dir, dataset_id)
      File "/home/travis/build/openml/openml-python/openml/datasets/functions.py", line 565, in _get_dataset_features
        features = xmltodict.parse(features_xml, force_list=('oml:feature',))["oml:data_features"]
      File "/home/travis/miniconda/envs/testenv/lib/python3.6/site-packages/xmltodict-0.11.0-py3.6.egg/xmltodict.py", line 330, in parse
        parser.Parse(xml_input, True)
    xml.parsers.expat.ExpatError: not well-formed (invalid token): line 321, column 325
```

Yes, my mistake. I added the values of nominal attributes to the openml database scheme, but I displayed them in sloppy xml. Should be fixed now.

**Comment by janvanrijn** [comment]
> I don't understand, nothing is supposed to have changed here. Since when is this doctest active and who wrote it?

The problem is the order. There is NO guarantee on the order in which the attributes are presented. I will add a skip for now, unless you have a better solution.

**Comment by mfeurer** [comment]
> The problem is the order. There is NO guarantee on the order in which the attributes are presented. I will add a skip for now, unless you have a better solution.

They used to be ordered alphabetically. Is there a reason that this changed?

> I feel like this is supposed to be a whole new PR

Yes, definitively!

**Comment by janvanrijn** [comment]
> They used to be ordered alphabetically. Is there a reason that this changed?

If it was in alphabetical order, this has been by 'coincidence'. There has never been logic in the code enforcing this, whatsoever. The fields are returned in the same order as the database presents them, which might (or might not) be semi-alphabetical based on which tasks are returned and which fields are present in the first tasks. 

This is also not easy to add without making the code more complicated, so I would prefer to not add nor define this. If you think otherwise please open an issue in the general openml issue tracker and we can discuss it there. 

Will merge for now, so we can move forward :)

**Pull request merged**
