### PR TITLE
String feature supports, use pandas dataframes

### PR DESCRIPTION
**Pull request by amueller**
This is a draft of adding string feature support via using pandas dataframes. I think using pandas would be nice to handle even float vs categorical etc. But that makes a lot of tests fail, in particular on dtypes.

After this change, columns can have very different dtypes. For example all null columns now have object dtype. Do we want to leave it like that?

### CODE REVIEW

**Comment by mfeurer** [comment]
This looks very promising. Can I somehow help here with comments etc?

**Comment by amueller** [comment]
Ugh, I forgot this wasn't done yet. Ping me? Take over? hrm...

**Comment by mfeurer** [comment]
I don't think anyone if Freiburg has capacities to take this over at the moment. I'm afraid it has to wait some time...

**Comment by joaquinvanschoren** [comment]
Hi all. Gael just reminded me that this is still open. Do we have some bandwidth now to look at this?

**Comment by mfeurer** [comment]
@glemaitre was working on this in #548 and wanted to continue on this, too.

**Comment by mfeurer** [comment]
Should be superseded by #548. Please reopen if this is not the case.

**Pull request closed without merging**
