### PR TITLE
MAINT update license information

### PR DESCRIPTION
**Pull request by mfeurer**

### CODE REVIEW

**Comment by amueller** [comment]
I am 100% in favor. In theory, you need to check this with any author of any code in the project. Given that the project is still relatively small, I think you should probably try.

**Comment by amueller** [comment]
Here are authors that still have lines in the code:
```
> for FILE in $(git ls-files) ; do git blame $FILE --porcelain | grep "^author " ; done | sort | uniq

author Anatolii Domashnev
author Andreas Mueller
author Jan van Rijn
author Jesper van Engelen
author Joaquin Vanschoren
author Matthias Feurer
author Minori Inoue
author Pieter Gijsbers
author Randy Olson
author toon
author Zardaloop
```
(slightly cleaned)

**Comment by joaquinvanschoren** [comment]
@adomashnev @janvanrijn @engelen @mfeurer @minoriinoue @PG-TUe @rhiever @toontesting @zardaloop: we decided a while ago to license all OpenML code under BSD (3-clause). 
Since the code includes some code of you, we wanted to double-check if you are ok with this.
Please raise any objections by tomorrow.

**Comment by PG-TUe** [comment]
Not a problem for me.

**Comment by joaquinvanschoren** [comment]
No objections :)

**Pull request merged**
