### PR TITLE
replace __str__ by __repr__

### PR DESCRIPTION
**Pull request by amueller**
Closes #739, #75

cc @Neeratyoy, @mfeurer

### CODE REVIEW

**Comment by amueller** [comment]
test failure in test_list_datasets_with_high_size_parameter seems unrelated?

**Comment by mfeurer** [comment]
> test failure in `test_list_datasets_with_high_size_parameter` seems unrelated?

yep, it is. This one might fail sporadically if we concurrently delete stuff from the test server.

**Comment by Neeratyoy** [comment]
Thanks a lot, @amueller.

**Comment by amueller** [comment]
Do you have an idea of why this fails on windows? That should be working, right?

**Comment by mfeurer** [comment]
Nope, maybe @PGijsbers knows. He (together with @WilliamRaynaut) set up the Windows tests and had some regex issues back then, too.

**Comment by PGijsbers** [comment]
I'm not sure. I tried the tests locally and they work on my Windows machine.

**Comment by amueller** [comment]
I might have gotten it.

**Comment by amueller** [comment]
hm still fails on linux on 3.5 :-/

**Comment by PGijsbers** [comment]
> I might have gotten it.

I saw you were working on fixing it, so I checked against older versions too. All commits in this PR left me with passing unit tests (at least those that `FAILED` on Appveyor when I was pinged).

**Comment by amueller** [comment]
failures seem unrelated now.

**Comment by amueller** [comment]
yay thank you!

**Pull request merged**
