### PR TITLE
Appveyor CI

### PR DESCRIPTION
**Pull request by PGijsbers**
Will request review when done. This is for easy reference of the changes+test results.

### CODE REVIEW

**Comment by PGijsbers** [comment]
@mfeurer @janvanrijn 
I'm getting an error in some unit tests that require uploading:
```
<p>Error Number: 1054</p><p>Unknown column 't.embargo_end_date' in 'field list'</p><p>SELECT t.task_id, t.embargo_end_date, tt.name, i.value AS did, d.name AS dname, ep.name AS epname FROM task_inputs i, task_inputs i2, estimation_procedure ep,
          task t, task_type tt, dataset d WHERE t.task_id = i.task_id AND t.task_id = i2.task_id AND i.input = 'source_data' AND i2.input = 'estimation_procedure' AND
          t.ttid = tt.ttid AND d.did = i.value AND ep.id = i2.value and t.task_id=119</p><p>Filename: models/abstract/Database_read.php</p><p>Line Number: 31
```

Should rebasing to the most current version of develop fix this?

**Comment by janvanrijn** [comment]
Not sure if this one is fixed by now, but this is one of @joaquinvanschoren s updates on the test server. Let's rerun the tests

**Comment by PGijsbers** [comment]
Thanks, rerunning the tests now!

**Comment by PGijsbers** [comment]
Getting [`openml.exceptions.OpenMLServerError: Unexpected server error. Please contact the developers!
Status code: 500`](https://travis-ci.org/openml/openml-python/jobs/364494923#L2439)

**Comment by PGijsbers** [comment]
Things seem to work! :)
I think there might be some optimizations left (I might have installed too much?).
But because I'll go on vacation I figured it might be best to round this up for now, and possibly improve later.
@mfeurer

**Comment by mfeurer** [comment]
Could you please rebase your commits on top of develop? Unfortunately, this one is really big and I think a lot of the changes are due to you merging develop into your branch.

**Comment by PGijsbers** [comment]
Huh, something went wrong with rebasing *again*. I don't get it. I'll see if I can fix it and otherwise I'll make another branch with all the changes *again*. I followed the instructions :(

**Comment by PGijsbers** [comment]
I tried to rebase and for some reason it suggests that I am behind develop. All in all I am a little confused, but I will simply create a new branch off of develop and apply the changes there, and put in a new pull request.

**Pull request closed without merging**
