### PR TITLE
Remove assertion on the test server

### LINKED ISSUE #858: `test__name_to_id_with_multiple_active_error` assumes there are multiple active public iris datasets on test server
this assumption is incorrect, as whenever the test server is resetted, there is only 1

### PR DESCRIPTION
**Pull request by mfeurer**
Closes #858 by using the live instead of the test server.

### CODE REVIEW

**Comment by PGijsbers** [comment]
Looks like tests fail due to server issues, otherwise the change looks good to me.

**Comment by mfeurer** [comment]
Yes, trying to fix them together with @janvanrijn (this PR is part of it).

**Comment by janvanrijn** [comment]
> Looks like tests fail due to server issues, otherwise the change looks good to me.

I disagree. 

The unit tests seem to assert that there are 2 public versions of the iris dataset on the test server, which is an incorrect assumption, especially after we reset the testserver.

**Comment by mfeurer** [comment]
> The unit tests seem to assert that there are 2 public versions of the iris dataset on the test server

This PR changes this. The unit test now assumes that there are 2 public versions of the iris dataset on the live server.

**Comment by janvanrijn** [comment]
That seems perfectly reasonable to me. This solves issue #858.

**Comment by PGijsbers** [comment]
I meant the CI results on this PR came back negative, but those were due to server issues. This was unrelated to the change made for this PR, which was not a server issue.

**Comment by janvanrijn** [comment]
can you point out specifically which failing unit tests you refer to?

Some might fail due to recent reset of test server.

**Comment by PGijsbers** [comment]
Errors like [this](https://travis-ci.org/openml/openml-python/jobs/604334447#L1671). I don't think they are persistent bugs, and might well have to do with the recent reset - I'm not saying the server is broken. But for the purpose of an `openml-python` PR I leave a comment indicating them as 'server issue' for later reference, indicating that we do see CI failures but don't expect them to be caused by the changes to `openml-python`.

**Pull request merged**
