### PR TITLE
[MRG]  EHN: support SparseDataFrame when creating a dataset 

### PR DESCRIPTION
**Pull request by glemaitre**
Add support for `SparseDataFrame` when creating a matrix.

### CODE REVIEW

**Comment by glemaitre** [comment]
@amueller @mfeurer @janvanrijn 

Here come the support for sparse dataframe during dataset creation.

**Comment by glemaitre** [comment]
ping @amueller @mfeurer @janvanrijn any feedback?

**Comment by janvanrijn** [comment]
Personally, I am not super familiar with sparse dataframes. I can have a look at your test-cases if you'd like and see whether they cover interesting test-cases.

**Comment by glemaitre** [comment]
@mfeurer I added a new section in the tutorial

**Comment by glemaitre** [comment]
Done!

**Pull request merged**
