### PR TITLE
slight cleanup of the notebooks

### PR DESCRIPTION
**Pull request by amueller**
python3 compat
don't call the connector openml
don't read a non-standard key file)

### CODE REVIEW

**Comment by mfeurer** [comment]
Is there any nice way to compare two ipynb's together?

**Comment by amueller** [comment]
no :(

**Comment by amueller** [comment]
here it is particularly bad because previously it was an old version of jupyter notebooks.

**Comment by mfeurer** [comment]
okay, I'll just merge it

**Pull request merged**
