### PR TITLE
MAINT prepare new release

### PR DESCRIPTION
**Pull request by mfeurer**
This PR prepares a new release.

### CODE REVIEW

**Comment by janvanrijn** [comment]
Can we try to have #567 in the release as well? I can contribute the example today

**Comment by glemaitre** [comment]
What is the release schedule. I'll like to have #548 as well and I am willing to finish it up right away.

**Comment by mfeurer** [comment]
There's not really a release schedule yet and there's no hurry at all. My motivation was to get things out as it has been a while since the last release and there have been multiple new issues for problems which we have already solved in the development branch. Therefore, I'm happy to wait for both PRs to have a nice and consistent release. However, it would be great to get this done within the next few days.

**Comment by joaquinvanschoren** [comment]
Regression (https://github.com/openml/openml-python/pull/560) as well please :)

**Comment by mfeurer** [comment]
What's the current status of #560? I know that the other two are almost done, but I did not follow the regression PR.

**Comment by joaquinvanschoren** [comment]
It was done, and we did the requested change to enums.
There were some merge conflicts because develop changed. I resolved those, but tests are now failing because of an import error. Looking into that now.

**Comment by janvanrijn** [comment]
Cool! Let me know when #560 is ready for review and I will go through it again.

**Comment by janvanrijn** [comment]
Another pretty important issue that should definitely be solved: #569 

I will create a PR tomorrow.

**Comment by mfeurer** [comment]
ping @janvanrijn

**Pull request merged**
