### PR TITLE
add tag_entity as backend

### LINKED ISSUE #619: duplicate functions tags
all entities (`data`, `flow`, etc) have a `push_tag` and `remove_tag` function, but this functionality is also implemented in `utils.py` with the function `_tag_entity` (tags and untags). Let's drop either of these functionalities (or at least make the `push_tag` and `remove_tag` functions use `_tag_entity` as backend)

### PR DESCRIPTION
**Pull request by sahithyaravi1493**
#### What does this PR implement/fix? Explain your changes.
modified `push_tag` and `remove_tag` functions to call `tag_entity`

### CODE REVIEW

**Comment by mfeurer** [comment]
Sorry, but there's still an unused import. You can perform this check locally be running `bash ci_scripts/flake_diff.sh`.

**Comment by sahithyaravi1493** [comment]
> Sorry, but there's still an unused import. You can perform this check locally be running `bash ci_scripts/flake_diff.sh`.

No problem, I will run this locally and commit.

**Comment by sahithyaravi1493** [comment]
> > Sorry, but there's still an unused import. You can perform this check locally be running `bash ci_scripts/flake_diff.sh`.
> 
> No problem, I will run this locally and commit.

Ignore my current commits, there still seem to be some errors. 

I could not get flake8 locally to work due to some issues. So I fixed the errors thrown by pyflakes and pep8. However, there seem to be additional errors thrown here. Will check on this.

**Comment by mfeurer** [comment]
The new errors appear to be errors raised by mypy.

Would it help you if the output of the two checkers would be separated?

**Comment by sahithyaravi1493** [comment]
> The new errors appear to be errors raised by mypy.
> 
> Would it help you if the output of the two checkers would be separated?

Hi Matthias,  Yes it would help. 

I am unable to run flake8 locally, due to an error caused by a space in my user folder. It seemed to be a bit tricky to rename the user folder. So,  I tried to run pyflakes and fix the warnings, assuming it would fix the import errors, but those fixes now resulted in mypy errors.

**Pull request merged**
